// grammar for the language.  very WIP

program     = { declaration* }

declaration = { useDecl
              | fnDecl
              | typeDecl
              }

useDecl     = { "use" ~ identifier ~ ( "::" ~ identifier )* }

identifier  = { alpha ~ ( alpha
                        | digit
                        )*
              }

alpha       = { "_"
              | 'a'..'z'
              | 'A'..'Z'
              }

digit       = { '0'..'9' }

fnDecl      = { TODO }

typeDecl    = { TODO }
